/*
 * This file is generated by jOOQ.
 */
package jhi.gummyworms.codegen.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import jhi.gummyworms.codegen.Gummyworms;
import jhi.gummyworms.codegen.Keys;
import jhi.gummyworms.codegen.tables.Trophicgroupings.TrophicgroupingsPath;
import jhi.gummyworms.codegen.tables.records.GenusRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Genus extends TableImpl<GenusRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>gummyworms.genus</code>
     */
    public static final Genus GENUS = new Genus();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GenusRecord> getRecordType() {
        return GenusRecord.class;
    }

    /**
     * The column <code>gummyworms.genus.GenusID</code>.
     */
    public final TableField<GenusRecord, Integer> GENUSID = createField(DSL.name("GenusID"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>gummyworms.genus.Name</code>.
     */
    public final TableField<GenusRecord, String> NAME = createField(DSL.name("Name"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>gummyworms.genus.TrophicID</code>.
     */
    public final TableField<GenusRecord, Integer> TROPHICID = createField(DSL.name("TrophicID"), SQLDataType.INTEGER, this, "");

    private Genus(Name alias, Table<GenusRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Genus(Name alias, Table<GenusRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>gummyworms.genus</code> table reference
     */
    public Genus(String alias) {
        this(DSL.name(alias), GENUS);
    }

    /**
     * Create an aliased <code>gummyworms.genus</code> table reference
     */
    public Genus(Name alias) {
        this(alias, GENUS);
    }

    /**
     * Create a <code>gummyworms.genus</code> table reference
     */
    public Genus() {
        this(DSL.name("genus"), null);
    }

    public <O extends Record> Genus(Table<O> path, ForeignKey<O, GenusRecord> childPath, InverseForeignKey<O, GenusRecord> parentPath) {
        super(path, childPath, parentPath, GENUS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class GenusPath extends Genus implements Path<GenusRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> GenusPath(Table<O> path, ForeignKey<O, GenusRecord> childPath, InverseForeignKey<O, GenusRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private GenusPath(Name alias, Table<GenusRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public GenusPath as(String alias) {
            return new GenusPath(DSL.name(alias), this);
        }

        @Override
        public GenusPath as(Name alias) {
            return new GenusPath(alias, this);
        }

        @Override
        public GenusPath as(Table<?> alias) {
            return new GenusPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Gummyworms.GUMMYWORMS;
    }

    @Override
    public Identity<GenusRecord, Integer> getIdentity() {
        return (Identity<GenusRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<GenusRecord> getPrimaryKey() {
        return Keys.KEY_GENUS_PRIMARY;
    }

    @Override
    public List<ForeignKey<GenusRecord, ?>> getReferences() {
        return Arrays.asList(Keys.TROPHICID);
    }

    private transient TrophicgroupingsPath _trophicgroupings;

    /**
     * Get the implicit join path to the
     * <code>gummyworms.trophicgroupings</code> table.
     */
    public TrophicgroupingsPath trophicgroupings() {
        if (_trophicgroupings == null)
            _trophicgroupings = new TrophicgroupingsPath(this, Keys.TROPHICID, null);

        return _trophicgroupings;
    }

    @Override
    public Genus as(String alias) {
        return new Genus(DSL.name(alias), this);
    }

    @Override
    public Genus as(Name alias) {
        return new Genus(alias, this);
    }

    @Override
    public Genus as(Table<?> alias) {
        return new Genus(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Genus rename(String name) {
        return new Genus(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Genus rename(Name name) {
        return new Genus(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Genus rename(Table<?> name) {
        return new Genus(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Genus where(Condition condition) {
        return new Genus(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Genus where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Genus where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Genus where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Genus where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Genus where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Genus where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Genus where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Genus whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Genus whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
