/*
 * This file is generated by jOOQ.
 */
package jhi.gummyworms.codegen.tables;


import java.util.Collection;

import jhi.gummyworms.codegen.Gummyworms;
import jhi.gummyworms.codegen.tables.records.GenusToTrophicGroupingRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GenusToTrophicGrouping extends TableImpl<GenusToTrophicGroupingRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>gummyworms.genus_to_trophic_grouping</code>
     */
    public static final GenusToTrophicGrouping GENUS_TO_TROPHIC_GROUPING = new GenusToTrophicGrouping();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GenusToTrophicGroupingRecord> getRecordType() {
        return GenusToTrophicGroupingRecord.class;
    }

    /**
     * The column <code>gummyworms.genus_to_trophic_grouping.genusName</code>.
     */
    public final TableField<GenusToTrophicGroupingRecord, String> GENUSNAME = createField(DSL.name("genusName"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column
     * <code>gummyworms.genus_to_trophic_grouping.trophicGrouping</code>.
     */
    public final TableField<GenusToTrophicGroupingRecord, String> TROPHICGROUPING = createField(DSL.name("trophicGrouping"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>gummyworms.genus_to_trophic_grouping.trophicID</code>.
     */
    public final TableField<GenusToTrophicGroupingRecord, Integer> TROPHICID = createField(DSL.name("trophicID"), SQLDataType.INTEGER, this, "");

    private GenusToTrophicGrouping(Name alias, Table<GenusToTrophicGroupingRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private GenusToTrophicGrouping(Name alias, Table<GenusToTrophicGroupingRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.view("create view `genus_to_trophic_grouping` as select `gummyworms`.`genus`.`Name` AS `genusName`,`gummyworms`.`trophicgroupings`.`TrophicGrouping` AS `trophicGrouping`,`gummyworms`.`genus`.`TrophicID` AS `trophicID` from (`gummyworms`.`genus` join `gummyworms`.`trophicgroupings` on((`gummyworms`.`genus`.`TrophicID` = `gummyworms`.`trophicgroupings`.`TrophicID`)))"), where);
    }

    /**
     * Create an aliased <code>gummyworms.genus_to_trophic_grouping</code> table
     * reference
     */
    public GenusToTrophicGrouping(String alias) {
        this(DSL.name(alias), GENUS_TO_TROPHIC_GROUPING);
    }

    /**
     * Create an aliased <code>gummyworms.genus_to_trophic_grouping</code> table
     * reference
     */
    public GenusToTrophicGrouping(Name alias) {
        this(alias, GENUS_TO_TROPHIC_GROUPING);
    }

    /**
     * Create a <code>gummyworms.genus_to_trophic_grouping</code> table
     * reference
     */
    public GenusToTrophicGrouping() {
        this(DSL.name("genus_to_trophic_grouping"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Gummyworms.GUMMYWORMS;
    }

    @Override
    public GenusToTrophicGrouping as(String alias) {
        return new GenusToTrophicGrouping(DSL.name(alias), this);
    }

    @Override
    public GenusToTrophicGrouping as(Name alias) {
        return new GenusToTrophicGrouping(alias, this);
    }

    @Override
    public GenusToTrophicGrouping as(Table<?> alias) {
        return new GenusToTrophicGrouping(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public GenusToTrophicGrouping rename(String name) {
        return new GenusToTrophicGrouping(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GenusToTrophicGrouping rename(Name name) {
        return new GenusToTrophicGrouping(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public GenusToTrophicGrouping rename(Table<?> name) {
        return new GenusToTrophicGrouping(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GenusToTrophicGrouping where(Condition condition) {
        return new GenusToTrophicGrouping(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GenusToTrophicGrouping where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GenusToTrophicGrouping where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GenusToTrophicGrouping where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GenusToTrophicGrouping where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GenusToTrophicGrouping where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GenusToTrophicGrouping where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GenusToTrophicGrouping where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GenusToTrophicGrouping whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GenusToTrophicGrouping whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
