/*
 * This file is generated by jOOQ.
 */
package jhi.gummyworms.codegen.tables;


import java.util.Collection;

import jhi.gummyworms.codegen.Gummyworms;
import jhi.gummyworms.codegen.Keys;
import jhi.gummyworms.codegen.tables.Genus.GenusPath;
import jhi.gummyworms.codegen.tables.records.TrophicgroupingsRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Trophicgroupings extends TableImpl<TrophicgroupingsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>gummyworms.trophicgroupings</code>
     */
    public static final Trophicgroupings TROPHICGROUPINGS = new Trophicgroupings();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TrophicgroupingsRecord> getRecordType() {
        return TrophicgroupingsRecord.class;
    }

    /**
     * The column <code>gummyworms.trophicgroupings.TrophicID</code>.
     */
    public final TableField<TrophicgroupingsRecord, Integer> TROPHICID = createField(DSL.name("TrophicID"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>gummyworms.trophicgroupings.TrophicGrouping</code>.
     */
    public final TableField<TrophicgroupingsRecord, String> TROPHICGROUPING = createField(DSL.name("TrophicGrouping"), SQLDataType.VARCHAR(255), this, "");

    private Trophicgroupings(Name alias, Table<TrophicgroupingsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Trophicgroupings(Name alias, Table<TrophicgroupingsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>gummyworms.trophicgroupings</code> table
     * reference
     */
    public Trophicgroupings(String alias) {
        this(DSL.name(alias), TROPHICGROUPINGS);
    }

    /**
     * Create an aliased <code>gummyworms.trophicgroupings</code> table
     * reference
     */
    public Trophicgroupings(Name alias) {
        this(alias, TROPHICGROUPINGS);
    }

    /**
     * Create a <code>gummyworms.trophicgroupings</code> table reference
     */
    public Trophicgroupings() {
        this(DSL.name("trophicgroupings"), null);
    }

    public <O extends Record> Trophicgroupings(Table<O> path, ForeignKey<O, TrophicgroupingsRecord> childPath, InverseForeignKey<O, TrophicgroupingsRecord> parentPath) {
        super(path, childPath, parentPath, TROPHICGROUPINGS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class TrophicgroupingsPath extends Trophicgroupings implements Path<TrophicgroupingsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> TrophicgroupingsPath(Table<O> path, ForeignKey<O, TrophicgroupingsRecord> childPath, InverseForeignKey<O, TrophicgroupingsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private TrophicgroupingsPath(Name alias, Table<TrophicgroupingsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public TrophicgroupingsPath as(String alias) {
            return new TrophicgroupingsPath(DSL.name(alias), this);
        }

        @Override
        public TrophicgroupingsPath as(Name alias) {
            return new TrophicgroupingsPath(alias, this);
        }

        @Override
        public TrophicgroupingsPath as(Table<?> alias) {
            return new TrophicgroupingsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Gummyworms.GUMMYWORMS;
    }

    @Override
    public Identity<TrophicgroupingsRecord, Integer> getIdentity() {
        return (Identity<TrophicgroupingsRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<TrophicgroupingsRecord> getPrimaryKey() {
        return Keys.KEY_TROPHICGROUPINGS_PRIMARY;
    }

    private transient GenusPath _genus;

    /**
     * Get the implicit to-many join path to the <code>gummyworms.genus</code>
     * table
     */
    public GenusPath genus() {
        if (_genus == null)
            _genus = new GenusPath(this, null, Keys.TROPHICID.getInverseKey());

        return _genus;
    }

    @Override
    public Trophicgroupings as(String alias) {
        return new Trophicgroupings(DSL.name(alias), this);
    }

    @Override
    public Trophicgroupings as(Name alias) {
        return new Trophicgroupings(alias, this);
    }

    @Override
    public Trophicgroupings as(Table<?> alias) {
        return new Trophicgroupings(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Trophicgroupings rename(String name) {
        return new Trophicgroupings(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Trophicgroupings rename(Name name) {
        return new Trophicgroupings(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Trophicgroupings rename(Table<?> name) {
        return new Trophicgroupings(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Trophicgroupings where(Condition condition) {
        return new Trophicgroupings(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Trophicgroupings where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Trophicgroupings where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Trophicgroupings where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Trophicgroupings where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Trophicgroupings where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Trophicgroupings where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Trophicgroupings where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Trophicgroupings whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Trophicgroupings whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
