/*
 * This file is generated by jOOQ.
 */
package jhi.gummyworms.codegen.tables.records;


import jhi.gummyworms.codegen.tables.GenusToTrophicGrouping;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GenusToTrophicGroupingRecord extends TableRecordImpl<GenusToTrophicGroupingRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>gummyworms.genus_to_trophic_grouping.genusName</code>.
     */
    public void setGenusname(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>gummyworms.genus_to_trophic_grouping.genusName</code>.
     */
    public String getGenusname() {
        return (String) get(0);
    }

    /**
     * Setter for
     * <code>gummyworms.genus_to_trophic_grouping.trophicGrouping</code>.
     */
    public void setTrophicgrouping(String value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>gummyworms.genus_to_trophic_grouping.trophicGrouping</code>.
     */
    public String getTrophicgrouping() {
        return (String) get(1);
    }

    /**
     * Setter for <code>gummyworms.genus_to_trophic_grouping.trophicID</code>.
     */
    public void setTrophicid(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>gummyworms.genus_to_trophic_grouping.trophicID</code>.
     */
    public Integer getTrophicid() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GenusToTrophicGroupingRecord
     */
    public GenusToTrophicGroupingRecord() {
        super(GenusToTrophicGrouping.GENUS_TO_TROPHIC_GROUPING);
    }

    /**
     * Create a detached, initialised GenusToTrophicGroupingRecord
     */
    public GenusToTrophicGroupingRecord(String genusname, String trophicgrouping, Integer trophicid) {
        super(GenusToTrophicGrouping.GENUS_TO_TROPHIC_GROUPING);

        setGenusname(genusname);
        setTrophicgrouping(trophicgrouping);
        setTrophicid(trophicid);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised GenusToTrophicGroupingRecord
     */
    public GenusToTrophicGroupingRecord(jhi.gummyworms.codegen.tables.pojos.GenusToTrophicGrouping value) {
        super(GenusToTrophicGrouping.GENUS_TO_TROPHIC_GROUPING);

        if (value != null) {
            setGenusname(value.getGenusname());
            setTrophicgrouping(value.getTrophicgrouping());
            setTrophicid(value.getTrophicid());
            resetTouchedOnNotNull();
        }
    }
}
