/*
 * This file is generated by jOOQ.
 */
package jhi.gummyworms.codegen.tables.records;


import jhi.gummyworms.codegen.tables.Genus;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GenusRecord extends UpdatableRecordImpl<GenusRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>gummyworms.genus.GenusID</code>.
     */
    public void setGenusid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>gummyworms.genus.GenusID</code>.
     */
    public Integer getGenusid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>gummyworms.genus.Name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>gummyworms.genus.Name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>gummyworms.genus.TrophicID</code>.
     */
    public void setTrophicid(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>gummyworms.genus.TrophicID</code>.
     */
    public Integer getTrophicid() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GenusRecord
     */
    public GenusRecord() {
        super(Genus.GENUS);
    }

    /**
     * Create a detached, initialised GenusRecord
     */
    public GenusRecord(Integer genusid, String name, Integer trophicid) {
        super(Genus.GENUS);

        setGenusid(genusid);
        setName(name);
        setTrophicid(trophicid);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised GenusRecord
     */
    public GenusRecord(jhi.gummyworms.codegen.tables.pojos.Genus value) {
        super(Genus.GENUS);

        if (value != null) {
            setGenusid(value.getGenusid());
            setName(value.getName());
            setTrophicid(value.getTrophicid());
            resetTouchedOnNotNull();
        }
    }
}
