/*
 * This file is generated by jOOQ.
 */
package jhi.gummyworms.codegen.tables.records;


import jhi.gummyworms.codegen.tables.Trophicgroupings;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TrophicgroupingsRecord extends UpdatableRecordImpl<TrophicgroupingsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>gummyworms.trophicgroupings.TrophicID</code>.
     */
    public void setTrophicid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>gummyworms.trophicgroupings.TrophicID</code>.
     */
    public Integer getTrophicid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>gummyworms.trophicgroupings.TrophicGrouping</code>.
     */
    public void setTrophicgrouping(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>gummyworms.trophicgroupings.TrophicGrouping</code>.
     */
    public String getTrophicgrouping() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TrophicgroupingsRecord
     */
    public TrophicgroupingsRecord() {
        super(Trophicgroupings.TROPHICGROUPINGS);
    }

    /**
     * Create a detached, initialised TrophicgroupingsRecord
     */
    public TrophicgroupingsRecord(Integer trophicid, String trophicgrouping) {
        super(Trophicgroupings.TROPHICGROUPINGS);

        setTrophicid(trophicid);
        setTrophicgrouping(trophicgrouping);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised TrophicgroupingsRecord
     */
    public TrophicgroupingsRecord(jhi.gummyworms.codegen.tables.pojos.Trophicgroupings value) {
        super(Trophicgroupings.TROPHICGROUPINGS);

        if (value != null) {
            setTrophicid(value.getTrophicid());
            setTrophicgrouping(value.getTrophicgrouping());
            resetTouchedOnNotNull();
        }
    }
}
