/*
 * This file is generated by jOOQ.
 */
package jhi.gummyworms.codegen;


import java.util.Arrays;
import java.util.List;

import jhi.gummyworms.codegen.tables.Genus;
import jhi.gummyworms.codegen.tables.GenusToTrophicGrouping;
import jhi.gummyworms.codegen.tables.Trophicgroupings;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Gummyworms extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>gummyworms</code>
     */
    public static final Gummyworms GUMMYWORMS = new Gummyworms();

    /**
     * The table <code>gummyworms.genus</code>.
     */
    public final Genus GENUS = Genus.GENUS;

    /**
     * The table <code>gummyworms.genus_to_trophic_grouping</code>.
     */
    public final GenusToTrophicGrouping GENUS_TO_TROPHIC_GROUPING = GenusToTrophicGrouping.GENUS_TO_TROPHIC_GROUPING;

    /**
     * The table <code>gummyworms.trophicgroupings</code>.
     */
    public final Trophicgroupings TROPHICGROUPINGS = Trophicgroupings.TROPHICGROUPINGS;

    /**
     * No further instances allowed
     */
    private Gummyworms() {
        super(DSL.name("gummyworms"), null, DSL.comment(""));
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Genus.GENUS,
            GenusToTrophicGrouping.GENUS_TO_TROPHIC_GROUPING,
            Trophicgroupings.TROPHICGROUPINGS
        );
    }
}
