/*
 * This file is generated by jOOQ.
 */
package jhi.gummyworms.codegen;


import jhi.gummyworms.codegen.tables.Genus;
import jhi.gummyworms.codegen.tables.Trophicgroupings;
import jhi.gummyworms.codegen.tables.records.GenusRecord;
import jhi.gummyworms.codegen.tables.records.TrophicgroupingsRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.QOM.ForeignKeyRule;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * gummyworms.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<GenusRecord> KEY_GENUS_PRIMARY = Internal.createUniqueKey(Genus.GENUS, DSL.name("KEY_genus_PRIMARY"), new TableField[] { Genus.GENUS.GENUSID }, true);
    public static final UniqueKey<TrophicgroupingsRecord> KEY_TROPHICGROUPINGS_PRIMARY = Internal.createUniqueKey(Trophicgroupings.TROPHICGROUPINGS, DSL.name("KEY_trophicgroupings_PRIMARY"), new TableField[] { Trophicgroupings.TROPHICGROUPINGS.TROPHICID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<GenusRecord, TrophicgroupingsRecord> TROPHICID = Internal.createForeignKey(Genus.GENUS, DSL.name("TrophicID"), new TableField[] { Genus.GENUS.TROPHICID }, Keys.KEY_TROPHICGROUPINGS_PRIMARY, new TableField[] { Trophicgroupings.TROPHICGROUPINGS.TROPHICID }, true, ForeignKeyRule.RESTRICT, ForeignKeyRule.RESTRICT);
}
