/*
 * This file is generated by jOOQ.
 */
package jhi.gummyworms.codegen;


import jhi.gummyworms.codegen.tables.Genus;
import jhi.gummyworms.codegen.tables.GenusToTrophicGrouping;
import jhi.gummyworms.codegen.tables.Trophicgroupings;


/**
 * Convenience access to all tables in gummyworms.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>gummyworms.genus</code>.
     */
    public static final Genus GENUS = Genus.GENUS;

    /**
     * The table <code>gummyworms.genus_to_trophic_grouping</code>.
     */
    public static final GenusToTrophicGrouping GENUS_TO_TROPHIC_GROUPING = GenusToTrophicGrouping.GENUS_TO_TROPHIC_GROUPING;

    /**
     * The table <code>gummyworms.trophicgroupings</code>.
     */
    public static final Trophicgroupings TROPHICGROUPINGS = Trophicgroupings.TROPHICGROUPINGS;
}
