/*
 * This file is generated by jOOQ.
 */
package jhi.gummyworms.codegen.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Genus implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer genusid;
    private String name;
    private Integer trophicid;

    public Genus() {}

    public Genus(Genus value) {
        this.genusid = value.genusid;
        this.name = value.name;
        this.trophicid = value.trophicid;
    }

    public Genus(
        Integer genusid,
        String name,
        Integer trophicid
    ) {
        this.genusid = genusid;
        this.name = name;
        this.trophicid = trophicid;
    }

    /**
     * Getter for <code>gummyworms.genus.GenusID</code>.
     */
    public Integer getGenusid() {
        return this.genusid;
    }

    /**
     * Setter for <code>gummyworms.genus.GenusID</code>.
     */
    public void setGenusid(Integer genusid) {
        this.genusid = genusid;
    }

    /**
     * Getter for <code>gummyworms.genus.Name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>gummyworms.genus.Name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>gummyworms.genus.TrophicID</code>.
     */
    public Integer getTrophicid() {
        return this.trophicid;
    }

    /**
     * Setter for <code>gummyworms.genus.TrophicID</code>.
     */
    public void setTrophicid(Integer trophicid) {
        this.trophicid = trophicid;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Genus other = (Genus) obj;
        if (this.genusid == null) {
            if (other.genusid != null)
                return false;
        }
        else if (!this.genusid.equals(other.genusid))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.trophicid == null) {
            if (other.trophicid != null)
                return false;
        }
        else if (!this.trophicid.equals(other.trophicid))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.genusid == null) ? 0 : this.genusid.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.trophicid == null) ? 0 : this.trophicid.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Genus (");

        sb.append(genusid);
        sb.append(", ").append(name);
        sb.append(", ").append(trophicid);

        sb.append(")");
        return sb.toString();
    }
}
