/*
 * This file is generated by jOOQ.
 */
package jhi.gummyworms.codegen.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GenusToTrophicGrouping implements Serializable {

    private static final long serialVersionUID = 1L;

    private String genusname;
    private String trophicgrouping;
    private Integer trophicid;

    public GenusToTrophicGrouping() {}

    public GenusToTrophicGrouping(GenusToTrophicGrouping value) {
        this.genusname = value.genusname;
        this.trophicgrouping = value.trophicgrouping;
        this.trophicid = value.trophicid;
    }

    public GenusToTrophicGrouping(
        String genusname,
        String trophicgrouping,
        Integer trophicid
    ) {
        this.genusname = genusname;
        this.trophicgrouping = trophicgrouping;
        this.trophicid = trophicid;
    }

    /**
     * Getter for <code>gummyworms.genus_to_trophic_grouping.genusName</code>.
     */
    public String getGenusname() {
        return this.genusname;
    }

    /**
     * Setter for <code>gummyworms.genus_to_trophic_grouping.genusName</code>.
     */
    public void setGenusname(String genusname) {
        this.genusname = genusname;
    }

    /**
     * Getter for
     * <code>gummyworms.genus_to_trophic_grouping.trophicGrouping</code>.
     */
    public String getTrophicgrouping() {
        return this.trophicgrouping;
    }

    /**
     * Setter for
     * <code>gummyworms.genus_to_trophic_grouping.trophicGrouping</code>.
     */
    public void setTrophicgrouping(String trophicgrouping) {
        this.trophicgrouping = trophicgrouping;
    }

    /**
     * Getter for <code>gummyworms.genus_to_trophic_grouping.trophicID</code>.
     */
    public Integer getTrophicid() {
        return this.trophicid;
    }

    /**
     * Setter for <code>gummyworms.genus_to_trophic_grouping.trophicID</code>.
     */
    public void setTrophicid(Integer trophicid) {
        this.trophicid = trophicid;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final GenusToTrophicGrouping other = (GenusToTrophicGrouping) obj;
        if (this.genusname == null) {
            if (other.genusname != null)
                return false;
        }
        else if (!this.genusname.equals(other.genusname))
            return false;
        if (this.trophicgrouping == null) {
            if (other.trophicgrouping != null)
                return false;
        }
        else if (!this.trophicgrouping.equals(other.trophicgrouping))
            return false;
        if (this.trophicid == null) {
            if (other.trophicid != null)
                return false;
        }
        else if (!this.trophicid.equals(other.trophicid))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.genusname == null) ? 0 : this.genusname.hashCode());
        result = prime * result + ((this.trophicgrouping == null) ? 0 : this.trophicgrouping.hashCode());
        result = prime * result + ((this.trophicid == null) ? 0 : this.trophicid.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("GenusToTrophicGrouping (");

        sb.append(genusname);
        sb.append(", ").append(trophicgrouping);
        sb.append(", ").append(trophicid);

        sb.append(")");
        return sb.toString();
    }
}
