/*
 * This file is generated by jOOQ.
 */
package jhi.gummyworms.codegen.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Trophicgroupings implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer trophicid;
    private String trophicgrouping;

    public Trophicgroupings() {}

    public Trophicgroupings(Trophicgroupings value) {
        this.trophicid = value.trophicid;
        this.trophicgrouping = value.trophicgrouping;
    }

    public Trophicgroupings(
        Integer trophicid,
        String trophicgrouping
    ) {
        this.trophicid = trophicid;
        this.trophicgrouping = trophicgrouping;
    }

    /**
     * Getter for <code>gummyworms.trophicgroupings.TrophicID</code>.
     */
    public Integer getTrophicid() {
        return this.trophicid;
    }

    /**
     * Setter for <code>gummyworms.trophicgroupings.TrophicID</code>.
     */
    public void setTrophicid(Integer trophicid) {
        this.trophicid = trophicid;
    }

    /**
     * Getter for <code>gummyworms.trophicgroupings.TrophicGrouping</code>.
     */
    public String getTrophicgrouping() {
        return this.trophicgrouping;
    }

    /**
     * Setter for <code>gummyworms.trophicgroupings.TrophicGrouping</code>.
     */
    public void setTrophicgrouping(String trophicgrouping) {
        this.trophicgrouping = trophicgrouping;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Trophicgroupings other = (Trophicgroupings) obj;
        if (this.trophicid == null) {
            if (other.trophicid != null)
                return false;
        }
        else if (!this.trophicid.equals(other.trophicid))
            return false;
        if (this.trophicgrouping == null) {
            if (other.trophicgrouping != null)
                return false;
        }
        else if (!this.trophicgrouping.equals(other.trophicgrouping))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.trophicid == null) ? 0 : this.trophicid.hashCode());
        result = prime * result + ((this.trophicgrouping == null) ? 0 : this.trophicgrouping.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Trophicgroupings (");

        sb.append(trophicid);
        sb.append(", ").append(trophicgrouping);

        sb.append(")");
        return sb.toString();
    }
}
